### ISSUE TITLE
Export Functionalty Removed

### ISSUE THREAD

**Issue by AllegisChambers** [newrelic/nr1-cloud-optimize#108]
## Summary

Previously, we were able to export the results into at least CSV to be loaded and analyzed offline and swizzled into various tools and reports. With the launch of the new tool, we cannot find a way to export this data.

## Desired Behaviour

While viewing an optimization report, we should at least be able to export the existing view.

## Possible Solution

A simple export button to export the current view in a simple format such as CSV

## Additional context

We often have to export and analyze this data for various leadership reporting and commentary/planning purposes.

**Comment by Kav91** [comment]
Have added a full raw json export in [v3.13.0](https://github.com/newrelic/nr1-cloud-optimize/releases/tag/v3.13.0).
Note the data structure is not a simple flat csv as before since we've expanded to cater for many new entity types which have different attributes/columns in their respective tables, it includes everything including tags for the targeted entities. 
The public catalog version should be updated shortly to reflect this change.

**Comment by Kav91** [comment]
Closing as the application has an export json data feature now. Feel free to re-open if any concerns.
