### ISSUE TITLE
Firefox issue for first run of Cloud Optimize

### ISSUE THREAD

**Issue by Performance-First** [newrelic/nr1-cloud-optimize#50]
Firefox issue for first run of Cloud Optimize

First run of the Cloud Optimizer results in everything running hard to the right. 

The Cloud Optimize app in NR1 appears to have an overflow tag, that when removed, fixes the issue. Customer is seeing it as he tries to run it for the first time. To double check I used Demotron and saw the same result, including an incognito window. Please see screenshots.
![image (3) (1)](https://user-images.githubusercontent.com/67280230/85304571-84c49000-b471-11ea-9b27-d94ffc5e1e47.png)
![image (4) (1)](https://user-images.githubusercontent.com/67280230/85304574-85f5bd00-b471-11ea-8e8b-d88ab0dcd4fa.png)

**Comment by Kav91** [comment]
This should be fixed in 2.2.0 once this PR is merged -> https://github.com/newrelic/nr1-catalog/pull/90 .
I enforced some minimum widths to prevent this, rather then remove the overflow as that behaviour is different with chrome.

If it reoccurs once the catalog version is rolled out, please feel free to reopen.
