### ISSUE TITLE
Filter out container entities

### ISSUE THREAD

**Issue by iamfuzz** [newrelic/nr1-cloud-optimize#63]
## Filter out container entities by default

If a customer is currently running a number of containers in, for example, AWS Fargate, Cloud Optimize will list those entities.  Given the dynamic nature here, this can result in thousands of entities being displayed that the user must scroll through/sort  before getting to useful information. 

## Desired Behaviour

Entities with no optimization recommendation should be hidden by default.

**Comment by Kav91** [comment]
@iamfuzz can you share an example of this, containers are not first class entities in the platform I have never seen this behaviour before.
If the infra agent is running in a container and detects the underlying host, by design of how the agent and platform works it will report that EC2. The samples returned from containers don't even align with the standard SystemSample event so I don't see how this is possible at all.

**Comment by iamfuzz** [comment]
@Kav91 

Hey Kav,

I guess this was just a bad assumption on my part then.  I was working with a user who is seeing thousands of stale entities and we had assumed it was due to Fargate churn.   I'll see if I can get him to add more color here directly.
